### ISSUE TITLE
curl请求https报错

### ISSUE THREAD

**Issue by jifegg** [killme2008/leancloud-php-library#4]
SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

可以通过设定证书解决：
curl_setopt($c, CURLOPT_SSL_VERIFYPEER, true); ;
curl_setopt($c, CURLOPT_CAINFO, dirname(__FILE__).'/cacert.pem');

**Comment by killme2008** [comment]
已经修复，谢谢。
